OpenStack-AD-Migrate/etc/openstack-utils/config.ini
OpenStack-AD-Migrate/usr/local/bin/openstack-ad-migrate.py

Read a config file to get the credentials to use rather than having them hardcoded within the script

Move to reading a config file for credentials

---

OpenStack-AD-Migrate/etc/openstack-utils/config.ini
OpenStack-AD-Migrate/usr/local/bin/openstack-ad-migrate.py
OpenStack-SecurityGroup-Create-Project/usr/local/bin/openstack-securitygroup-create-project
OpenStack-SecurityGroup-Create-Project/usr/local/bin/openstack-securitygroup-update-project

Move to using JSON to read in the list of groups and allow groups to be mapped to projects which dont match the group name. Also add ability to map different roles to group members.
Add sourcing of the OpenStack credentials file
Add a script for managing Security Groups for projects and imposing sets of rules.
Also some renaming of variables to make the code more readable

Groups JSON, Sourcing Credentials file and Managing Security Groups

---

OpenStack-Rabbit-Consumer/etc/openstack-utils/consumer.ini
OpenStack-Rabbit-Consumer/usr/local/bin/aq_manage.py
OpenStack-Rabbit-Consumer/usr/local/bin/consumer.py

Consumes messages from rabbit mq and runs aquilon commands based on
certain messages
github is confusing so i made a new repo

Rabbit MQ Consumer

---

OpenStack-Rabbit-Consumer/etc/openstack-utils/rabbit-consumer/aq_manage.py
OpenStack-Rabbit-Consumer/etc/openstack-utils/rabbit-consumer/consumer.py

fixed final bug

---

OpenStack-AD-Migrate/usr/local/bin/openstack-ad-migrate.py

some whitespace changes and fixes adding users

Fix  logic so that users actually get added

---

OpenStack_get_username/var/www/cgi-bin/get_username.sh

Adds a script to be run as a cgi script to get a username from an instance id.

Add script to get username when provided with instance id

---

README.md

I'm happy to explain the other bits as well if someone can explain to me what they do!

Update README to reflect scope of repo

---

OpenStack-Rally-Tester/usr/local/bin/rally-extract-results
OpenStack-Rally-Tester/usr/local/bin/rally-run-test

Fixxed rally updater, this one has been running in prod for many months.

Updating with fixxed rally-run-test

---

OpenStack-Rabbit-Consumer/usr/local/bin/aq_api.py
OpenStack-Rabbit-Consumer/usr/local/bin/message_consumer.py
OpenStack-Rabbit-Consumer/usr/local/bin/openstack_api.py

Adds functionality to create and delete hosts and machines in Aquilon
Also  now gets default values from the image metadata if the same values are not filled in on the instance metadata

Aquilon Hook Add and Delete hosts

---

OpenStack-Rabbit-Consumer/.pylintrc
OpenStack-Rabbit-Consumer/rabbit_consumer/aq_api.py
OpenStack-Rabbit-Consumer/rabbit_consumer/message_consumer.py
OpenStack-Rabbit-Consumer/test/test_aq_api.py

Fixes the warnings detected in the aq_api file by Pylint

Fix pylint warnings in aq api

---

OpenStack-Rabbit-Consumer/rabbit_consumer/message_consumer.py
OpenStack-Rabbit-Consumer/test/test_message_consumer.py

Adds tests for methods in message_consumer 
Refactoring will come in the next PR, as we're already ~1k LOC churn

Add tests for methods in message_consumer

---

OpenStack-Rabbit-Consumer/rabbit_consumer/aq_api.py
OpenStack-Rabbit-Consumer/rabbit_consumer/aq_fields.py
OpenStack-Rabbit-Consumer/rabbit_consumer/consumer_config.py
OpenStack-Rabbit-Consumer/rabbit_consumer/message_consumer.py
OpenStack-Rabbit-Consumer/rabbit_consumer/openstack_api.py
OpenStack-Rabbit-Consumer/test/test_aq_api.py
OpenStack-Rabbit-Consumer/test/test_message_consumer.py
OpenStack-Rabbit-Consumer/test/test_openstack_api.py

This should resolve the errors about it being too long, too many locals and make it easier to refactor individual steps ...etc.

Fix remaining pylint warnings

---

.github/workflows/black.yaml
.github/workflows/capi_image_build.yaml
capi_image_builder/.pylintrc
capi_image_builder/builder/git_ops.py
capi_image_builder/main.py
capi_image_builder/requirements.txt
capi_image_builder/test/test_git_ops.py

Adds the framework for handling the complex git ops we're going to do later on and associated unit tests

Add Git Operations for future CAPI Image Builder

---

capi_image_builder/builder/packer.py
capi_image_builder/test/test_packer.py

Adds steps to invoke Packer and the associated test for these new methods

Add pack script and tests

---

capi_image_builder/builder/__init__.py
capi_image_builder/builder/image_ops.py
capi_image_builder/main.py
capi_image_builder/test/test_image_ops.py
capi_image_builder/test/test_main.py

Adds steps to rotate images after upload and deactivate the existing image(s)

Image rotation

---

charts/rabbit-consumer/Chart.yaml

Bumps the chart to pull in the hotfix for the rabbit loggers

Bump chart to new rabbit consumer version

---

.github/workflows/rabbit_consumer_chart.yaml
charts/rabbit-consumer/Chart.yaml
charts/rabbit-consumer/staging-values.yaml
charts/rabbit-consumer/templates/deployment.yaml

Fixes the chart getting the incorrect version

Fix chart not getting version

---

.github/workflows/iriscast_package_build.yaml

Add RPM to release - to get it added to repos.gridpp

Update Iriscasttools Workflow

---

OpenStack-nova-accounting/extract_accounting.py

This means that vande will show and aggregate the CPU flavors

Add in nulls for gpu fields for cpu flavors

---

.github/workflows/iriscast_package_build.yaml
iriscasttools/setup.py

point to python3.6/site-packages instead of 3.6.8/site-packages
sorry my mistake here

fix to point to /usr/lib/python3.6 instead of /usr/lib/3.6.8

---

.github/workflows/iriscast_package_build.yaml
iriscasttools/setup.py

changed 'python-version' to 'python_version'

iriscasttools path not set properly

---

OpenStack-Rabbit-Consumer/rabbit_consumer/aq_api.py
OpenStack-Rabbit-Consumer/rabbit_consumer/aq_metadata.py
OpenStack-Rabbit-Consumer/rabbit_consumer/consumer_config.py
OpenStack-Rabbit-Consumer/rabbit_consumer/message_consumer.py
OpenStack-Rabbit-Consumer/rabbit_consumer/openstack_address.py
OpenStack-Rabbit-Consumer/rabbit_consumer/openstack_api.py
OpenStack-Rabbit-Consumer/rabbit_consumer/rabbit_message.py
OpenStack-Rabbit-Consumer/rabbit_consumer/vm_data.py

Added module docstrings that were missing for the rabbit consumers

DOC: Add missing module docstrings

---

pynetbox_data_uploader/.pylintrc
pynetbox_data_uploader/lib/user_methods/csv_to_netbox.py
pynetbox_data_uploader/lib/utils/csv_to_dataclass.py
pynetbox_data_uploader/lib/utils/dataclass_data.py
pynetbox_data_uploader/lib/utils/format_dict.py
pynetbox_data_uploader/tests/test_csv_to_dataclass.py
pynetbox_data_uploader/tests/test_format_dict.py
pynetbox_data_uploader/tests/test_netbox_get_id.py

Created the device dataclass. Created 2 methods to take the csv file and create a dataclass object for each class.

Dictionaries to dataclass

---

.github/workflows/MonitoringTools.yaml
MonitoringTools/.coveragerc
MonitoringTools/.pylintrc
MonitoringTools/pytest.ini
MonitoringTools/requirements.txt
MonitoringTools/tests/test_limits_to_influx.py
MonitoringTools/tests/test_send_metric_utils.py
MonitoringTools/tests/test_service_status_to_influx.py
MonitoringTools/tests/test_slottifier.py
MonitoringTools/tests/test_slottifier_entry.py
MonitoringTools/usr/local/bin/limits_to_influx.py
MonitoringTools/usr/local/bin/send_metric_utils.py
MonitoringTools/usr/local/bin/service_status_to_influx.py
MonitoringTools/usr/local/bin/slottifier.py
MonitoringTools/usr/local/bin/slottifier_entry.py

Added a Github workflow for Pytest, Pylint, Codecov

ENH: Added CI/CD for this folder

---

OpenStack_get_username/var/www/cgi-bin/get_username_list.sh

This script was on the service nodes but missing from this repo

Add in get_username_list script from service nodes

---

.github/workflows/codeql.yml

Added CodeQL workflows to the repository.

Added CodeQL for codescanning.

---

README.md

Added changes to the read.md file for jira task.

Added changes to read.md file to make it more updated

---

terraform_provisioning/README.md
terraform_provisioning/priv_network.tf
terraform_provisioning/variables.tf
terraform_provisioning/vars.tfvars

Adds a terraform script to create (and destroy) a private network within openstack!

add terraform script to make a private network

---

grafana_monitoring/README.md

Quick fix to the documentation - renaming the README and moving the hashes

DOC: Quick fix to documentation

---

README.md
terraform_provisioning/README.md

Quick update to add terraform_provisioning to main README

DOC: update to add terraform_provisioning to main README

---

README.md
wex_llm_app/README.md

This project is for the WEX students to work on.

DOC: Added a directory and read me for a project.

---

charts/rabbit-consumer/Chart.yaml

update chart so we can fix 400 error on make command

MAINT: update rabbit consumer chart for app 3.0.1

---

.github/dependabot.yml

This workflow will create pull requests for all outdated github action versions

ENH: Add a dependabot workflow

---

.github/workflows/bin/version_increment.sh
.github/workflows/rabbit_consumer_schedule.yaml

Pulls the latest container dependencies on a weekly basis. Created a bash script to increment the patch each time it runs. Created a separate yaml file for the scheduling so that the version doesn't increment on a pull or push. Commits the version.txt file to master.

Added scheduled job to build rabbit consumers and increment patch

---

README.md

MAINT: Add codecov badge to repo

---

.github/workflows/rabbit_consumer_schedule.yaml

Added creating a new branch to the existing step to commit changes. Added step to create a PR for merging changes from new branch.

Update rabbit_consumer_schedule.yaml to create PR

---

.github/workflows/black.yaml

Missed part from deleting rabbit from this repo

MAINT: Remove Rabbit Consumer from black workflow

---

README.md
Weekly-Reporting/README.md
Weekly-Reporting/data.yaml
Weekly-Reporting/export.py

This weekly reporting script will upload data to an influx database to be displayed on the Cloud Grafana dashboards. It is a working prototype

Add weekly reporting script

---

README.md
chatops_deployment/.gitignore
chatops_deployment/README.md

Create terraform and ansible project layout. Updated README with new project description.

Initial project commit

---

Alertmanager/silence-alerts.sh

Adding a util script to silence alertmanager alerts on a given list of hosts, tested and working

Alertmanager Silence Utility
