- OpenStack-Rabbit-Consumer/etc/openstack-utils/consumer.ini
everything after the `=` is interpreted as the value, so the quotes break things.
> Removed quotes from consumer.ini

- OpenStack-Rally-Tester/usr/local/bin/rally-extract-results
- OpenStack-Rally-Tester/usr/local/bin/rally-run-test
****rally-run-test****
* Added line to create `/tmp/results/` directory if absent
* If multiple `rally task results ...` lines exist, this will only use the first one. Rally benchmarks launched from the same task are stored under the same ID.
****rally-extract-results****
* Added timestamp to output
* Added image name to output when task is `VMTasks.boot_runcommand_delete`
> Updates to Rally Scripts

- capi_image_builder/.pylintrc
- capi_image_builder/builder/args.py
- capi_image_builder/builder/git_ops.py
- capi_image_builder/builder/git_steps.py
- capi_image_builder/builder/image_ops.py
- capi_image_builder/builder/packer.py
- capi_image_builder/main.py
- capi_image_builder/requirements.txt
- capi_image_builder/test/test_git_ops.py
- capi_image_builder/test/test_git_steps.py
- capi_image_builder/test/test_image_ops.py
- capi_image_builder/test/test_main.py
- capi_image_builder/test/test_packer.py
- Wires the various steps together
- Adds directory handling
- Openstack steps to upload the image
- Associated tests
We still need to (in a future PR):
- Cleanup a tmp directory if a user specified one
- Push the rebased repo to Github on completion
To test:
Setup a `clouds.yaml` file with the `openstack` cloud, such that `openstack --os-cloud openstack server list` returns something sane
```bash
cd SCD-Openstack-Utils/capi_image_builder
python3 -m venv venv 
source venv/bin/activate
python3 -m pip install requirements.txt
python3 main.py ~/.ssh/id_rsa.pub
```
Note this requires us to use a pub key system so we can later upload the image (not implemented as of this PR)
> Add main method to capi_image_builder

- capi_image_builder/builder/image_ops.py
The date was coming up 2023YYY-03M-13D, as the date specifiers expect a single char rather than a char per output space
> Fix date on final images

- .github/workflows/capi_image_build.yaml
- .github/workflows/rabbit_consumer.yaml
This changes the CI and CD workflows to only run on changed code, not
everything (except the formatter which is fast).
Against master it will always build everything for sanity.
> CI and CD improvements

- .github/workflows/iriscast_package_build.yaml
Update workflow to build package wheel
Updae workflow to create automated releases when merged to master
> Update iriscasttools workflow

- gpu_benchmark/benchmark.sh
- gpu_benchmark/gpu_setup.sh
- gpu_benchmark/power_perf.sh
- gpu_benchmark/readme.md
The previous implementation was IO bound on higher performance cards. Instead we switch to:
Phoronix Test Suite - This runs per card benchmarks and outputs the total run time
Hashcat - This acts as a stress test and captures power data
> Use Hashcat and Phoronix to benchmark

- .github/workflows/iriscast_package_build.yaml
separate out building rpms and wheel as two distinct steps - build multiple RPMs for different python versions 
- most notably python3.6 which is required for package to work on HVs
Previous PR #61 built RPM against python 3.11 - which doesn't work on HVs
> Release Multiple RPM Versions

- .github/workflows/black.yaml
- .github/workflows/iriscast_package_build.yaml
quick fix - sub-versions didn't match for python 3.6 RPM in #62
> build RPM for 3.6.8 instead of 3.6.15

- charts/rabbit-consumer/Chart.yaml
Bumps the chart to point to the new rabbit consumer version "upstream" changes
> Bump chart to point to new rabbit consumers

- aq_zombie_finder/aq_zombie_finder.py
- dns_entry_checker/dns_entry_checker.py
- dns_entry_checker/test/test_dns_entry_checker.py
GitHub doesn't include empty folders, so as such a check is required to ensure that the output folder exists, either by default or where specified.
> Ensure output directory exists

- .gitignore
- Netbox_CSV_Read/CSV/csv_utils.py
- Netbox_CSV_Read/CSV/format_dict.py
- Netbox_CSV_Read/Enums/dcim_device_id.py
- Netbox_CSV_Read/Enums/dcim_device_no_id.py
- Netbox_CSV_Read/Netbox_Api/netbox_connect.py
- Netbox_CSV_Read/Netbox_Api/netbox_data.py
- Netbox_CSV_Read/Netbox_Api/netbox_dcim.py
- Netbox_CSV_Read/Tests/test_netbox_connect.py
Pynetbox friendly dictionaries
> Added the format_dict.py module that converts normal csv dictionaries to Netbox friendly dictionaries.

- pynetbox_data_uploader/lib/netbox_api/netbox_get_id.py
- pynetbox_data_uploader/tests/test_netbox_get_id.py
Added tests for the above method and changed some enums stuff in the code. Removed attributes from netbox_get_id class as these enums will not be changed therefore do not need to be assigned.
> Written tests for get_id_from_key method.

- pynetbox_data_uploader/lib/utils/csv_to_dataclass.py
A change in the previous PR de-indented the return in the with open(). This caused an error becaused in the return statement the list funcition is used on the reader object but no operations can be done on the reader object outside of the context manager.
The pylint will still fail on import errors. I am fixing this. Just noticed this bug which renders the code useless. :)
> BUG: Read csv operation on closed file error.

- MonitoringTools/tests/test_limits_to_influx.py
- MonitoringTools/tests/test_send_metric_utils.py
- MonitoringTools/tests/test_service_status_to_influx.py
- MonitoringTools/tests/test_slottifier.py
- MonitoringTools/tests/test_slottifier_entry.py
- MonitoringTools/usr/local/bin/influxdb.conf
- MonitoringTools/usr/local/bin/limits_to_influx.py
- MonitoringTools/usr/local/bin/send_metric_utils.py
- MonitoringTools/usr/local/bin/service_status_to_influx.py
- MonitoringTools/usr/local/bin/slottifier.py
- MonitoringTools/usr/local/bin/slottifier_entry.py
Add scripts that scrape info from openstack that we post to influxdb - and use in our grafana dashboards. 
TODO: 
- ~~Unit Tests~~
- Add docstrings to tests
- CI/CD
-  convert limits_to_influx to only using openstacksdk
updated version of #22
> ENH: add grafana monitoring scripts

- MonitoringTools/tests/test_service_status_to_influx.py
- MonitoringTools/tests/test_slottifier.py
- MonitoringTools/tests/test_slottifier_entry.py
- MonitoringTools/usr/local/bin/service_status_to_influx.py
- MonitoringTools/usr/local/bin/slottifier.py
slottifier now only selects hvs with matching storagetype and hosttype to calculate slots on
fix data string formatting for `service_status_to_influx.py` script
> BUG: fix various bugs with influxdb monitoring scripts

- grafana_monitoring/README.md
- grafana_monitoring/compose.yaml
- grafana_monitoring/haproxy.cfg
Planned addition of ha-proxy to the grafana monitoring!
> Ha proxy addition

- README.md
- grafana_monitoring/compose.yaml
In compose.yaml 
- GF_GRAFANA_DOMAIN_NAME=$GRAFANA_DOMAIN_NAME
- GRAFANA_ROOT_URL=$GRAFANA_ROOT_URL
changed to
- GF_SERVER_DOMAIN_NAME=$GRAFANA_DOMAIN_NAME
- GF_SERVER_ROOT_URL=$GRAFANA_ROOT_URL
> BUG: Amended environment variables GRAFANA with GF

- .github/workflows/MonitoringTools.yaml
- .github/workflows/cloud_chatops.yaml
- .github/workflows/prometheus_query_to_csv.yaml
- .github/workflows/pynetbox.yaml
- .github/workflows/rabbit_consumer.yaml
- .github/workflows/reverse_ssl_cert_chain.yaml
Ensures we use codecov V4 and have a token for each build pipeline too
> MAINT: Update to codecov v4 and use tokens for all

- cloud_chatops/src/custom_exceptions.py
- cloud_chatops/src/get_github_prs.py
- cloud_chatops/src/main.py
- cloud_chatops/src/online_notif.py
- cloud_chatops/src/pr_dataclass.py
- cloud_chatops/src/pr_reminder.py
- cloud_chatops/src/read_data.py
- cloud_chatops/src/slack_app.py
- cloud_chatops/tests/test_read_data.py
This branch extends the current classes and improves the code readability using dataclasses.
The pylint errors here are fixed in #143
> Extending classes no dir

- .github/workflows/MonitoringTools.yaml
- .github/workflows/Openstack-Rally-Tester.yaml
- .github/workflows/aq_zombie_finder.yaml
- .github/workflows/black.yaml
- .github/workflows/cloud_chatops.yaml
- .github/workflows/dns_entry_checker.yaml
- .github/workflows/gpu_benchmark.yaml
- .github/workflows/iriscast_package_build.yaml
- .github/workflows/jsm_metric_collection.yaml
- .github/workflows/prometheus_query_to_csv.yaml
- .github/workflows/pynetbox.yaml
- .github/workflows/rabbit_consumer.yaml
- .github/workflows/rabbit_consumer_chart.yaml
- .github/workflows/reverse_ssl_cert_chain.yaml
- .github/workflows/word_cloud_generator.yaml
Updated the checkout and setup-python actions versions as they are the most commonly used.
Considering most people just copy paste workflow to workflow they never get updated/reviewed
> ENH: Update actions versions

- .github/workflows/cloud_chatops.yaml
The workflow was running on every PR which is wrong. It should run only when files in cloud_chatops dir are changed or the workflow itself
> BUG: Workflow runs only on certain changes

- .github/workflows/rabbit_consumer.yaml
New staging secrets have been added to the repo and so the dev push job should use these secrets
> ENH: Changed rabbit harbor access

- .github/workflows/rabbit_consumer_schedule.yaml
We don't need to push to the staging area since this is running on a schedule and no PRs will be made on this workflow. Therefore I removed it from the `rabbit_consumer_schedule.yaml` file only.
> Cleanup - removing the push to dev job on the Rabbit Consumer Schedule workflow

- MonitoringTools/requirements.txt
- MonitoringTools/tests/test_slottifier.py
- MonitoringTools/usr/local/bin/influxdb.conf
- MonitoringTools/usr/local/bin/slottifier.py
The flavor slot calculations have not been working since the OpenStack upgrades. Instead of changing the API calls in the Slottifier script, we have opted to use the Query Library instead so that we don't need to maintain Slottifier as much. The query library now obtains the openstack resources and we format it into a dictionary. 
Additionally, some of the dictionary keys have changed and therefore needed to be named accordingly and some key values may return "Not Found", therefore we needed to account for that too.
> Change Slottifier to use the Query Library to fix the slot calculations

- grafana_monitoring/README.md
- grafana_monitoring/roles/certbot/tasks/main.yml
- grafana_monitoring/roles/haproxy/tasks/main.yml
- grafana_monitoring/site.yml
We can no longer use certificates from DI so we are using let's encrypt as an alternative. LE certificates only last 90 days so we need to use certbot to automatically renew the certificates
> ENH: Add a certbot role to setup let's encrypt certificates

- .github/workflows/chatops.yaml
Check the terraform config is valid and run ansible lint and shellcheck
> ENH: Add a GitHub workflow for the chatops directory

- grafana_monitoring/roles/grafana/templates/grafana.ini.j2
Changing the default role to admin so people can make changes to datasources
> MAINT: Change the dev grafana IRIS IAM role from Editor to Admin

- chatops_deployment/ansible/roles/alertmanager/files/alertmanager.service
- chatops_deployment/ansible/roles/alertmanager/handlers/main.yml
- chatops_deployment/ansible/roles/alertmanager/tasks/main.yml
- chatops_deployment/ansible/roles/prometheus/files/prometheus.service
- chatops_deployment/ansible/roles/prometheus/files/rules.yml
- chatops_deployment/ansible/roles/prometheus/handlers/main.yml
- chatops_deployment/ansible/roles/prometheus/tasks/main.yml
Includes various fixes and improvements for Prometheus and Alertmanager
- Move Alertmanager and Prometheus logging from `/opt/<service>` into `/var/log/<service>`
- Simplify Alertmanager and Prometheus install by merging most tasks into unarchive and copy modules
- Fixes a doc typo
> Prometheus Alertmanager Fixes

- grafana_monitoring/roles/certbot/tasks/main.yml
- grafana_monitoring/roles/certbot/templates/renew_certs.sh.j2
(dev-)grafana.nubes.rl.ac.uk certificates were expiring due to certbot running whilst HAProxy was still active. Fixing this by stopping HAProxy before trying to renew. Also, merged all the cron jobs into a single script as it's a bit tidier. Tested and working
> Fixes Grafana certs not renewing

- grafana_monitoring/roles/grafana/tasks/main.yml
- grafana_monitoring/roles/grafana/templates/cloud_datasource.yaml.j2
- grafana_monitoring/roles/grafana/templates/grafana.ini.j2
- grafana_monitoring/roles/haproxy/templates/haproxy.cfg.j2
Various updates to the Grafana configuration. See commit messages for details.
> Updates to Cloud Grafana

- chatops_deployment/ansible/roles/elastic/tasks/kibana.yml
- chatops_deployment/ansible/roles/grafana/tasks/main.yml
- chatops_deployment/ansible/roles/grafana/templates/grafana.ini.j2
- chatops_deployment/ansible/roles/ssl_certificates/tasks/main.yml
- chatops_deployment/ansible/roles/ssl_certificates/tasks/ssl.yml
- chatops_deployment/ansible/roles/terraform/tasks/destroy.yml
Add a role to generate self signed certificates for most services. This allows us to enable https for communication between services.
> Self signed certs
